### ISSUE TITLE
Error when I run this script

### ISSUE THREAD

**Issue by swayamnarayan** [whisk3ykilo/hackerone2threadfix#1]
I get the below error when I run this script. Any possible reasons ?

`Traceback (most recent call last):
  File "hackerone2threadfix.py", line 59, in <module>
    id_list = [response["data"][id]["id"] for id in range(len(response["data"]))]
KeyError: 'data'`

**Comment by whiskeykilo** [comment]
I suspect that you may not be getting anything returned from the API, either because your H1 program has no reports or you're not authorized to read reports. Can you please add a print statement to print the `response` variable (before line 59 in the script, before line 10 in the snippet below) and post the output?

![carbon](https://user-images.githubusercontent.com/18176030/123872377-0364d080-d903-11eb-9f8c-72d52f1a7c6b.png)

**Comment by swayamnarayan** [comment]
It wasn't working with the API Token is generated as a Program but works when the token is generated as a user. The script works fine. Thanks !
